import '../models/cruise.dart';

class CruiseService {
  Cruise getMockCruise() {
    return Cruise(
      name: 'Волжское путешествие',
      shipName: 'Александр Невский',
      days: [
        DayItinerary(
          dayIndex: 1,
          dateLabel: '1 июня 2026',
          title: 'Астрахань — посадка',
          locationName: 'Астрахань',
          activities: [
            Activity(
              id: '1-1',
              title: 'Посадка на теплоход',
              description: 'Регистрация и размещение в каютах. Приветственный чай в ресторане.',
              type: ActivityType.meal,
              timeRange: '14:00 – 15:00',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 1,
            ),
            Activity(
              id: '1-2',
              title: 'Инструктаж по безопасности',
              description: 'Обязательный инструктаж для всех пассажиров: правила поведения на борту, расположение спасательных средств.',
              type: ActivityType.lecture,
              timeRange: '15:30 – 16:00',
              location: 'Конференц-зал, палуба 3',
              dayIndex: 1,
              lecturer: 'Старший помощник капитана',
            ),
            Activity(
              id: '1-3',
              title: 'Ужин — знакомство',
              description: 'Приветственный ужин с командой теплохода. Представление программы круиза.',
              type: ActivityType.meal,
              timeRange: '19:00 – 21:00',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 1,
            ),
          ],
        ),
        DayItinerary(
          dayIndex: 2,
          dateLabel: '2 июня 2026',
          title: 'Астрахань — экскурсия',
          locationName: 'Астрахань',
          activities: [
            Activity(
              id: '2-1',
              title: 'Завтрак',
              description: 'Шведский стол. Завтрак подаётся с 7:30 до 10:00.',
              type: ActivityType.meal,
              timeRange: '08:00 – 09:00',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 2,
            ),
            Activity(
              id: '2-2',
              title: 'Обзорная экскурсия по Астрахани',
              description: 'Автобусная экскурсия по городу: Астраханский кремль, набережная Волги, рынок «Селенские Исады».',
              type: ActivityType.excursion,
              timeRange: '09:30 – 13:00',
              location: 'Сбор у трапа',
              dayIndex: 2,
            ),
            Activity(
              id: '2-3',
              title: 'Обед',
              description: 'Обед в ресторане города (включён в программу).',
              type: ActivityType.meal,
              timeRange: '13:00 – 14:30',
              location: 'Ресторан «Лотос», г. Астрахань',
              dayIndex: 2,
            ),
            Activity(
              id: '2-4',
              title: 'Лекция: Флора и фауна дельты Волги',
              description: 'Научно-популярная лекция о природе Астраханского заповедника, редких видах птиц и рыб.',
              type: ActivityType.lecture,
              timeRange: '16:00 – 17:30',
              location: 'Конференц-зал, палуба 3',
              dayIndex: 2,
              lecturer: 'К.б.н. Ирина Петровна Морозова',
            ),
            Activity(
              id: '2-5',
              title: 'Ужин',
              description: 'Ужин в ресторане теплохода.',
              type: ActivityType.meal,
              timeRange: '19:00 – 20:30',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 2,
            ),
          ],
        ),
        DayItinerary(
          dayIndex: 3,
          dateLabel: '3 июня 2026',
          title: 'Мышкин',
          locationName: 'Мышкин — Углич',
          activities: [
            Activity(
              id: '3-1',
              title: 'Завтрак',
              description: 'Шведский стол.',
              type: ActivityType.meal,
              timeRange: '08:00 – 09:00',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 3,
            ),
            Activity(
              id: '3-2',
              title: 'История Мышкина: купеческий город',
              description: 'Погружение в историю одного из самых очаровательных городов на Волге. Узнайте, как мыши спасли город от Наполеона и почему Мышкин называют «городом купцов».',
              type: ActivityType.lecture,
              timeRange: '10:00 – 11:30',
              location: 'Конференц-зал, палуба 3',
              dayIndex: 3,
              lecturer: 'Анна Сергеевна Соколова',
            ),
            Activity(
              id: '3-3',
              title: 'Пешеходная экскурсия по Мышкину',
              description: 'Прогулка по городу: Музей Мыши, Успенский собор, набережная.',
              type: ActivityType.excursion,
              timeRange: '12:30 – 14:30',
              location: 'Сбор у трапа',
              dayIndex: 3,
            ),
            Activity(
              id: '3-4',
              title: 'Обед',
              description: 'Обед в ресторане теплохода.',
              type: ActivityType.meal,
              timeRange: '14:30 – 15:30',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 3,
            ),
            Activity(
              id: '3-5',
              title: 'Углич: история и легенды',
              description: 'Лекция об истории Углича: трагедия царевича Дмитрия, архитектура города, современный Углич.',
              type: ActivityType.lecture,
              timeRange: '16:00 – 17:30',
              location: 'Библиотека, палуба 2',
              dayIndex: 3,
              lecturer: 'Анна Сергеевна Соколова',
            ),
            Activity(
              id: '3-6',
              title: 'Ужин',
              description: 'Ужин с дегустацией местных сыров.',
              type: ActivityType.meal,
              timeRange: '19:00 – 20:30',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 3,
            ),
          ],
        ),
        DayItinerary(
          dayIndex: 4,
          dateLabel: '4 июня 2026',
          title: 'Углич — Мышкин',
          locationName: 'Углич',
          activities: [
            Activity(
              id: '4-1',
              title: 'Завтрак',
              description: 'Шведский стол.',
              type: ActivityType.meal,
              timeRange: '07:30 – 08:30',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 4,
            ),
            Activity(
              id: '4-2',
              title: 'Экскурсия по Угличу',
              description: 'Посещение Угличского кремля, церкви царевича Дмитрия на Крови, музея городского быта.',
              type: ActivityType.excursion,
              timeRange: '09:00 – 12:30',
              location: 'Сбор у трапа',
              dayIndex: 4,
            ),
            Activity(
              id: '4-3',
              title: 'Обед',
              description: 'Обед в ресторане теплохода.',
              type: ActivityType.meal,
              timeRange: '13:00 – 14:00',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 4,
            ),
            Activity(
              id: '4-4',
              title: 'Мастер-класс: роспись по дереву',
              description: 'Творческий мастер-класс от местных мастеров. Каждый участник заберёт с собой памятный сувенир.',
              type: ActivityType.lecture,
              timeRange: '15:00 – 16:30',
              location: 'Холл, палуба 1',
              dayIndex: 4,
              lecturer: 'Мастер ДПИ Елена Кузнецова',
            ),
            Activity(
              id: '4-5',
              title: 'Прощальный ужин',
              description: 'Торжественный ужин с музыкальной программой.',
              type: ActivityType.meal,
              timeRange: '19:00 – 22:00',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 4,
            ),
          ],
        ),
        DayItinerary(
          dayIndex: 5,
          dateLabel: '5 июня 2026',
          title: 'Москва — высадка',
          locationName: 'Москва',
          activities: [
            Activity(
              id: '5-1',
              title: 'Завтрак',
              description: 'Шведский стол.',
              type: ActivityType.meal,
              timeRange: '07:00 – 08:30',
              location: 'Ресторан «Волга», палуба 2',
              dayIndex: 5,
            ),
            Activity(
              id: '5-2',
              title: 'Высадка и прощание',
              description: 'Освобождение кают, получение багажа. Трансфер до автобусов.',
              type: ActivityType.excursion,
              timeRange: '09:00 – 10:00',
              location: 'Северный речной вокзал',
              dayIndex: 5,
            ),
          ],
        ),
      ],
    );
  }
}
